# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming]
        args:
          - "--max-line-length=140"

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length", "140"]

  # - repo: https://github.com/pre-commit/mirrors-yapf
  #   rev: v0.32.0
  #   hooks:
  #     - id: yapf
  #       args: ["--exclude", "cdk.out"]
  #       additional_dependencies: [toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "."]
        additional_dependencies: ["bandit[toml]"]
