# Deployment configuration

# AWS region where the stack will be deployed
DEPLOY_REGION: "us-west-2"

# Use cross-region-inference
CROSS_REGION_INFERENCE: True

# Add UUID suffix to resource names to avoid conflicts
ADD_UUID_NAMING: True

# Model ID for the smart (more capable) language model
SMART_LLM: "anthropic.claude-3-5-sonnet-20240620-v1:0"

# Model ID for the fast (less capable but quicker) language model
FAST_LLM: "anthropic.claude-3-haiku-20240307-v1:0"

# Lambda function names
WEBSEARCH_FUNCTION_NAME: "WebSearchFunction"
ADVANCED_SEARCH_FUNCTION_NAME: "AdvancedWebSearchFunction"

# Action group names
WEBSEARCH_ACTION_GROUP_NAME: "WebSearchActionGroup"
ADVANCED_SEARCH_ACTION_GROUP_NAME: "AdvancedWebSearchActionGroup"

# Agent name
AGENT_NAME: "WebSearchAgent"
